title: "min queue"
author:
  name: "min queue"
  email: mainqueue@ya.ru

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: "Исследую тонкости  и делюсь своими наблюдениями"
url: "https://mainqueue.github.io"

# Build settings
permalink: /:title/

theme: minima

header_pages:
  - index.md
  - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
show_excerpts: true

google_analytics: G-YYZ795831P

# Theme-specific settings

minima:
  social_links:
    - { platform: telegram,       user_url: "https://t.me/mainqueue" }
    - { platform: github,         user_url: "https://github.com/mainqueue" }

